// ─────────────────────────────────────────────────────────────────
//  server/routes/studio/kb_download.js
//  KB File Download Proxy — PERMANENT FIX
//
//  ROOT CAUSE CHAIN:
//    1. QB REST API returns /files/tableId/recordId/fieldId/version URLs
//    2. QB UI shows /up/tableId/g/... URLs — ONLY generated by QB UI, unreachable via API
//    3. Direct browser links to /up/ or /files/ require QB browser session cookie
//    4. Previous proxy tried fetching /up/ with QB-USER-TOKEN → 401 (wrong auth method)
//
//  PERMANENT SOLUTION:
//    - Store the QB REST /files/ URL during sync (no conversion)
//    - Proxy fetches via QB REST API v1: api.quickbase.com/v1/files/...
//    - QB REST API v1 accepts QB-USER-TOKEN → works 100%, no QB browser session needed
//    - User only needs to be authenticated in MUMS (JWT), not in QB browser
// ─────────────────────────────────────────────────────────────────
const { getUserFromJwt } = require('../../lib/supabase');
const { readSettings }   = require('../../services/quickbaseSync');

function sendError(res, code, msg) {
  res.statusCode = code;
  res.setHeader('Content-Type', 'text/plain');
  return res.end(msg);
}

// Convert any QB file URL format → QB REST API v1 files endpoint
// Handles:
//   /files/tableId/recordId/fieldId/version     (QB REST format — direct)
//   /up/tableId/a/r/recordId/e/fieldId/version  (QB UI format — parsed)
//   https://api.quickbase.com/v1/files/...       (already correct — passthrough)
function toQbApiFilesUrl(inputUrl, realm) {
  try {
    const u = new URL(String(inputUrl || ''));
    const segs = u.pathname.split('/').filter(Boolean);

    // Already a QB REST v1 files URL
    if (u.hostname === 'api.quickbase.com' && segs[0] === 'v1' && segs[1] === 'files') {
      return u.toString();
    }

    // QB realm URL with /files/tableId/recordId/fieldId[/version]
    if (segs[0] === 'files' && segs.length >= 4) {
      const [, tableId, recordId, fieldId, version = '1'] = segs;
      return `https://api.quickbase.com/v1/files/${tableId}/${recordId}/${fieldId}/${version}`;
    }

    // QB realm URL with /up/tableId/a/r/recordId/e/fieldId[/version]
    // Pattern: /up/{tableId}/a/r/{recordId}/e/{fieldId}/{version}
    if (segs[0] === 'up' && segs[2] === 'a' && segs[3] === 'r' && segs[5] === 'e') {
      const tableId  = segs[1];
      const recordId = segs[4];
      const fieldId  = segs[6];
      const version  = segs[7] || '1';
      if (tableId && recordId && fieldId) {
        return `https://api.quickbase.com/v1/files/${tableId}/${recordId}/${fieldId}/${version}`;
      }
    }

    // Unknown format — return null (will be handled as invalid)
    return null;
  } catch (_) {
    return null;
  }
}

// Validate that the URL targets a quickbase.com host (security check)
function isQbUrl(url) {
  try {
    const h = new URL(String(url || '')).hostname;
    return /\.quickbase\.com$/i.test(h) || h === 'api.quickbase.com';
  } catch (_) { return false; }
}

module.exports = async (req, res) => {
  try {
    res.setHeader('Cache-Control', 'no-store');

    // ── 1. Authenticate MUMS user (JWT) ──────────────────────────
    const auth = req.headers.authorization || '';
    const jwt  = auth.toLowerCase().startsWith('bearer ') ? auth.slice(7) : '';
    const user = await getUserFromJwt(jwt);
    if (!user) return sendError(res, 401, 'Unauthorized');

    // ── 2. Parse and validate the target URL ─────────────────────
    const src = req.query && req.query.url ? String(req.query.url) : '';
    if (!src) return sendError(res, 400, 'Missing url parameter');
    if (!isQbUrl(src)) return sendError(res, 400, 'Invalid host — must be quickbase.com');

    // ── 3. Load QB settings (realm + user token) ─────────────────
    const settingsOut = await readSettings();
    const settings    = (settingsOut.ok && settingsOut.settings) ? settingsOut.settings : {};
    const realm       = String(settings.quickbaseRealm || '').trim();
    const token       = String(settings.quickbaseUserToken || '').trim();

    if (!realm || !token) {
      console.error('[kb_download] QB settings missing — realm:', !!realm, 'token:', !!token);
      return sendError(res, 503, 'KB settings not configured — set Quickbase App URL and Token in General Settings');
    }

    // ── 4. Convert to QB REST API v1 files endpoint ───────────────
    // api.quickbase.com/v1/files accepts QB-USER-TOKEN header
    // This works regardless of QB browser session state
    const apiUrl = toQbApiFilesUrl(src, realm);

    if (!apiUrl) {
      // Unknown URL format — fall back to direct fetch of the original URL
      // This handles any QB URL format we haven't anticipated
      console.warn('[kb_download] Unknown QB URL format, fetching directly:', src);
    }

    const fetchUrl = apiUrl || src;
    console.log('[kb_download] user:', user.id, 'fetching:', fetchUrl);

    // ── 5. Fetch file from QB with USER TOKEN ─────────────────────
    const qbResp = await fetch(fetchUrl, {
      method: 'GET',
      headers: {
        'QB-Realm-Hostname': realm,
        'Authorization':     `QB-USER-TOKEN ${token}`,
        'User-Agent':        'MUMS-Support-Studio/1.0',
      },
    });

    if (!qbResp.ok) {
      const errText = await qbResp.text().catch(() => '');
      console.error('[kb_download] QB fetch failed:', qbResp.status, errText.slice(0, 200));
      return sendError(res, qbResp.status === 404 ? 404 : 502,
        `QB returned ${qbResp.status} — check that the QB User Token has file access`);
    }

    // ── 6. Stream file back to browser ───────────────────────────
    const body        = Buffer.from(await qbResp.arrayBuffer());
    const contentType = qbResp.headers.get('content-type') || 'application/octet-stream';
    const disposition = qbResp.headers.get('content-disposition') || 'attachment';

    res.statusCode = 200;
    res.setHeader('Content-Type', contentType);
    res.setHeader('Content-Disposition', disposition);
    res.setHeader('Content-Length', body.length);
    res.setHeader('Cache-Control', 'no-store');
    return res.end(body);

  } catch (err) {
    console.error('[kb_download] Unhandled error:', err);
    return sendError(res, 500, 'Internal server error');
  }
};
