const { serviceSelect, serviceUpsert } = require('../lib/supabase');
const { decryptText } = require('../lib/crypto');
const KB_SETTINGS_KEY = 'ss_kb_settings';
const KB_ITEMS_KEY = 'ss_kb_items';
function normalizeUrl(raw, realm) { const val = String(raw || '').trim(); if (!val) return ''; try { return new URL(val).toString(); } catch (_) { if (!realm) return ''; try { return new URL(val.replace(/^\/+/, ''), `https://${realm}`).toString(); } catch(__){ return ''; } } }
function parseQbUrl(url) { const out = { realm: '', tableId: '', qid: '' }; try { const u = new URL(String(url || '')); const m = String(u.hostname || '').match(/^([a-z0-9-]+)\.quickbase\.com$/i); if (m) out.realm = `${m[1]}.quickbase.com`; const segs = u.pathname.split('/').filter(Boolean); const ti = segs.indexOf('table'); if (ti >= 0 && segs[ti + 1]) out.tableId = segs[ti + 1]; const qidMatch = String(u.searchParams.get('qid') || '').match(/-?\d+/); if (qidMatch) out.qid = qidMatch[0]; } catch (_) {} return out; }
function pickFieldValue(record, fid) { const c = record && record[String(fid)]; const v = c && typeof c === 'object' ? c.value : ''; if (v == null) return ''; if (typeof v === 'string' || typeof v === 'number') return String(v); if (Array.isArray(v)) return v.map((x) => (x && typeof x === 'object' ? (x.url || x.value || x.name || '') : String(x || ''))).filter(Boolean).join(' | '); if (typeof v === 'object') return String(v.url || v.value || v.name || v.text || ''); return ''; }
function extractDownloadLinks(record, fields, realm) { const links = []; Object.entries(fields || {}).forEach(([fid, label]) => { const low = String(label || '').toLowerCase(); if (!low.includes('link') && !low.includes('download') && !low.includes('file')) return; const v = pickFieldValue(record, fid); if (!v) return; String(v).split('|').map((s) => s.trim()).filter(Boolean).forEach((candidate) => { const safe = normalizeUrl(candidate, realm); if (safe) links.push(safe); }); }); return Array.from(new Set(links)); }
async function readSettings() { const out = await serviceSelect('mums_documents', `select=key,value,updated_at&key=eq.${encodeURIComponent(KB_SETTINGS_KEY)}&limit=1`); if (!out.ok) return { ok: false, settings: {} }; const row = Array.isArray(out.json) && out.json[0] ? out.json[0] : null; const raw = row && row.value && typeof row.value === 'object' ? row.value : {}; const parsed = parseQbUrl(raw.quickbaseAppUrl || ''); return { ok: true, settings: { quickbaseAppUrl: String(raw.quickbaseAppUrl || '').trim(), quickbaseRealm: String(raw.quickbaseRealm || parsed.realm || '').trim(), quickbaseTableId: String(raw.quickbaseTableId || parsed.tableId || '').trim(), quickbaseQid: String(raw.quickbaseQid || parsed.qid || '').trim(), quickbaseUserToken: decryptText(raw.quickbaseUserToken || ''), syncSchedule: String(raw.syncSchedule || '').trim(), lastSyncedAt: raw.lastSyncedAt || null } }; }
async function readItems() { const out = await serviceSelect('mums_documents', `select=key,value,updated_at&key=eq.${encodeURIComponent(KB_ITEMS_KEY)}&limit=1`); if (!out.ok) return { ok: false, items: [] }; const row = Array.isArray(out.json) && out.json[0] ? out.json[0] : null; return { ok: true, items: Array.isArray(row && row.value && row.value.items) ? row.value.items : [], syncedAt: row && row.value ? (row.value.syncedAt || row.updated_at) : null }; }
async function writeItems(items, actor) { return serviceUpsert('mums_documents', [{ key: KB_ITEMS_KEY, value: { items, count: items.length, syncedAt: new Date().toISOString(), updatedByName: actor || null }, updated_at: new Date().toISOString(), updated_by_name: actor || null }], 'key'); }
async function fetchAllQuickbaseRecords(settings, opts = {}) { const { quickbaseTableId: tableId, quickbaseRealm: realm, quickbaseUserToken: token, quickbaseQid: qid } = settings || {}; if (!tableId || !realm || !token) throw new Error('quickbase_config_missing'); let skip = 0; const top = 250; const all = []; let fields = {}; for (let page = 0; page < 120; page += 1) { const body = { from: tableId, options: { skip, top } }; if (qid) body.queryId = qid; const resp = await fetch('https://api.quickbase.com/v1/records/query', { method: 'POST', headers: { 'QB-Realm-Hostname': realm, Authorization: `QB-USER-TOKEN ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!resp.ok) throw new Error(`quickbase_query_failed:${resp.status}`); const json = await resp.json(); if (json && json.fields) fields = json.fields; const rows = Array.isArray(json && json.data) ? json.data : []; all.push(...rows); if (rows.length < top) break; skip += rows.length; if (opts.sleepMs) await new Promise((r) => setTimeout(r, opts.sleepMs)); } return { records: all, fields }; }
function mapRecordToKbItem(record, fields, settings) { const id = pickFieldValue(record, 3) || `row-${Math.random().toString(36).slice(2, 9)}`; return { id: String(id), title: pickFieldValue(record, 6) || pickFieldValue(record, 7) || `Record ${id}`, type: pickFieldValue(record, 10) || 'Knowledge Base', related_product: pickFieldValue(record, 9), product_family: pickFieldValue(record, 13) || pickFieldValue(record, 14), download_url: extractDownloadLinks(record, fields, settings.quickbaseRealm), source_link: settings.quickbaseAppUrl || '', created_at: pickFieldValue(record, 1) || null, raw_json: record }; }
function dedupeById(items) { const m = new Map(); (items || []).forEach((it) => { if (it && it.id) m.set(String(it.id), it); }); return Array.from(m.values()); }
async function runKnowledgeBaseSync({ actorName } = {}) { const settingsOut = await readSettings(); if (!settingsOut.ok) throw new Error('settings_read_failed'); const quickbase = await fetchAllQuickbaseRecords(settingsOut.settings, { sleepMs: 120 }); const mapped = dedupeById((quickbase.records || []).map((r) => mapRecordToKbItem(r, quickbase.fields || {}, settingsOut.settings))); const w = await writeItems(mapped, actorName || 'system'); if (!w.ok) throw new Error('kb_items_write_failed'); return { ok: true, count: mapped.length, items: mapped, syncedAt: new Date().toISOString() }; }
module.exports = { KB_SETTINGS_KEY, KB_ITEMS_KEY, parseQbUrl, normalizeUrl, readSettings, readItems, fetchAllQuickbaseRecords, mapRecordToKbItem, dedupeById, runKnowledgeBaseSync };
